# Generated by Django 4.1.5 on 2023-03-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_ex',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
