# Generated by Django 4.1.5 on 2023-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0002_product_p_ex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ls',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('na', models.CharField(max_length=100)),
                ('de', models.CharField(max_length=100)),
                ('pr', models.IntegerField()),
                ('da', models.DateField()),
                ('eda', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='lsre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('na', models.CharField(max_length=100)),
                ('de', models.CharField(max_length=100)),
                ('pr', models.IntegerField()),
                ('da', models.DateField()),
                ('eda', models.DateField()),
            ],
        ),
    ]
