# Generated by Django 4.1.5 on 2023-03-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0004_vl'),
    ]

    operations = [
        migrations.CreateModel(
            name='vm',
            fields=[
                ('un', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('p', models.CharField(max_length=100)),
            ],
        ),
    ]
